# Competency Question 11
# What are the specific team characteristics values of a given agile profile?

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ag:   <http://www.semanticweb.org/utn/AgileOntology#>

SELECT  ?profile ?type ?value WHERE
{    	?profile rdf:type ag:AgileProfile ;
                       ag:hasTeam ?team .
    	?team   ag:hasTeamCharacteristic ?teamch .
    	?teamch ag:hasValue ?value;
                rdf:type ?type .
  		?type rdfs:subClassOf ag:TeamCharacteritic .
Filter (?profile = <http://www.semanticweb.org/utn/AgileOntology#Encuesta26>)
}
