# Competency Question 14
# Which iterations were carried out in a specific ASD project?

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ag:   <http://www.semanticweb.org/utn/AgileOntology#>

SELECT  ?profile ?iteration WHERE
{    	?profile rdf:type ag:AgileProfile ;
                       ag:hasProject ?project .
    	?project   ag:hasEvents ?iteration .
    	?iteration rdf:type ag:Iteration .
Filter (?profile = <http://www.semanticweb.org/utn/AgileOntology#Geniar>)
}
